FROM apache/airflow:2.9.1-python3.10

USER root
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    && apt-get clean

USER airflow

# Копируем файлы зависимостей и исходный код
COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY ./dags/ /opt/airflow/dags/
COPY ./src/ /opt/airflow/src/

ENV PYTHONPATH="/opt/airflow:${PYTHONPATH}"
